// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwF-IlshcRnthR1ImubiuRd0aH9Ntelww',
    appId: '1:181044346908:web:018c9d8b774ab4a78a1fd9',
    messagingSenderId: '181044346908',
    projectId: 'flutterfirebase-1e0d0',
    authDomain: 'flutterfirebase-1e0d0.firebaseapp.com',
    storageBucket: 'flutterfirebase-1e0d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjEITf-hrFy0XwK_aubPcneehwTa9Htk',
    appId: '1:181044346908:android:57fb513327e4dbd28a1fd9',
    messagingSenderId: '181044346908',
    projectId: 'flutterfirebase-1e0d0',
    storageBucket: 'flutterfirebase-1e0d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Mtz3OT56gTvYokDz8w3_NaQNQKdJNUU',
    appId: '1:181044346908:ios:24fb19af9e020e498a1fd9',
    messagingSenderId: '181044346908',
    projectId: 'flutterfirebase-1e0d0',
    storageBucket: 'flutterfirebase-1e0d0.appspot.com',
    iosBundleId: 'com.example.firebaseexampleapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Mtz3OT56gTvYokDz8w3_NaQNQKdJNUU',
    appId: '1:181044346908:ios:4a2637ac99683aed8a1fd9',
    messagingSenderId: '181044346908',
    projectId: 'flutterfirebase-1e0d0',
    storageBucket: 'flutterfirebase-1e0d0.appspot.com',
    iosBundleId: 'com.example.firebaseexampleapp.RunnerTests',
  );
}
